name: Publicar web

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: github-pages
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v5

      - name: Configurar GitHub Pages
        uses: actions/configure-pages@v5

      - name: Instalar Node.js
        uses: actions/setup-node@v5
        with:
          node-version: '24'

      - name: Instalar dependencias
        run: npm install

      - name: Generar web con Antora
        run: npx antora antora-playbook.yml

      - name: Preparar artefacto de Pages
        uses: actions/upload-pages-artifact@v4
        with:
          path: build/site

      - name: Publicar
        id: deployment
        uses: actions/deploy-pages@v4
